### ISSUE TITLE
Package extension

### ISSUE THREAD

**Issue by notabene** [ffoodd/a11y.css#292]
Depends on [Gulp zipping](https://github.com/ffoodd/a11y.css/issues/283) 

- [x] Firefox: package and deploy locally
- [x] Firefox: check storage
- [x] Firefox: publish on store
- [x] Chrome: package and deploy locally
- [x] Chrome: check storage
- [x] Chrome: publish on store

EDIT by @ffoodd 

* [x] close #325 and #340 (I think we're going with FR+EN only for now…)
* [x] improve UI in #346 
* [x] package webextensions
* [x] publish to Firefox add-on + Chrome webstore
* [x] update documentation website
* [x] update wiki (to document webextension itself)
  * [x] Assets pipeline (both in FR and EN)
  * [x] grouping pages through: usage (to include edge cases, customization and pipeline) and contribution (with doc and translation)
  * [x] add somehow webextension technical documentation (already started as a markdown file in `/webextension`) : scripts, translations, etc.
  * [x] and improve main README to at least include wiki's home & website's home contents.
* [x] update SassDoc theme for sidebar + main nav
* [x] merge on `master`
* [x] bump a major version (git tag + release + npm publish)

**Comment by notabene** [comment]
Zip works locally as per commit https://github.com/ffoodd/a11y.css/commit/803cefebc44e67b6e46414215bfc77c55cc9d59d

**Comment by notabene** [comment]
Firefox: done \o/

**Comment by ffoodd** [comment]
Packaging task and local upload works for Chromium.
Still needs browser compatibility improvement, though…

**Comment by ffoodd** [comment]
`checkAlts` is now fully working in Chromium! Just needs to check storage and publish on store.

IMHO starting an Edge version is probably  too much, since it'll switch to Blink soon. What's your opinion, @notabene ?

And FWIW, I'll try to improve UI too before release new version on stores.

**Comment by notabene** [comment]
Yes, let's remove Edge.

**Comment by notabene** [comment]
@ffoodd shouldn't this issue be closed if you're OK with Chrome? (can't test it, don't have it, don't want it) ;)

**Comment by ffoodd** [comment]
@notabene Still need to check storage (don't really know what to check) and to publish on store.

I'll finish #325 + try to close #340 (or document it), then improve UI a bit before releasing it to Chrome add-on webstore: that'll make (IMHO) the first milestone for webextension, meaning that I'll merge it to `master` and make it the official recommended usage.

So before it's done:
* [ ] close #325 and #340 (I think we're going with FR+EN only for now…)
* [ ] improve UI
* [ ] update documentation website + wiki
* [ ] merge on `master`
* [ ] bump a major version (git tag + release + npm publish)
* [ ] package webextensions
* [ ] publish to Firefox add-on + Chrome webstore
* [ ] drink something (this is where you get back in).

**Comment by ffoodd** [comment]
@notabene I just published a 1.0.6 on firefox add-ons (and currently waiting for approval on chrome's webstore). I’d like you to test a bit before definetely merging this first version on master, and recommending it as the main a11y.css usage on the wiki + website :)

I may have missed something…

**Comment by notabene** [comment]
Not good. As I told you the other day, I haven't found yet how to store a state when going from one tab to another. Your evolution does not work as expected.

Steps to reproduce:

1. open two tabs
2. in tab 1, toggle one option On
3. switch to tab 2
4. come back to tab 1: the option is Off although the setting is still applied to the page.

If you look into the Web Developer extension you'll see the same problem. I'm not sure an extension has the right to access a tab when you switch back to it.

I'd suggest keeping to the old formulation for now, and getting rid of the switch boxes.

**Comment by ffoodd** [comment]
@notabene Hii thanks for checking in!
I totally forgot this, focusing on UI. However!

I just pushed something: I managed to use storage for each setting, and it's working in both Firefox and Chromium. It's not done yet:
* [ ] in active tab, following a link to another page keeps the storage value; I'm not sure about what to do here: 
  1. cleaning storage when activating a link?
  2. keeping storage but activate setting on the new page?
* [ ] there's tons of duplicated code: it would be great to improve this (but I'll ask for help :p)
* [ ] I think `popuphandlers.js` is dead code, as well as `util.js`, isn't it?

FWIW we're getting closer and closer to a first fully working version, and that's nice!

**Comment by ffoodd** [comment]
Maybe @GaetanBt could help a bit?

**Comment by ffoodd** [comment]
After some tries, I managed to get the current tab id with @stefd code part in `checkAlts` :
```javascript
browser.tabs.query({ active: true, currentWindow: true }).then((tabs) => {
	console.log(tabs[0].id);
});
```
I don't know if I'll be able to make a helper for this, since `browser.tabs.getCurrent()` does not work (either missing permission, or not applicable in this context… maybe both).

Let's try by repeating this for now.

The only part missing now is to *use this to contextually store states and values for a specific tab*, and prevent a tab's values from override another one's.

**Comment by ffoodd** [comment]
@notabene I just pushed a 1.0.7 to Firefox add-ons, that correclty handle tab specific storage in FirefOx.

However this does not work on Chromium for now, and I have no idea why…

**Comment by ffoodd** [comment]
Working on the wiki, missing:
* [ ] Assets pipeline (both in FR and EN)
* [ ] grouping pages through: usage (to include edge cases, customization and pipeline) and contribution (with doc and translation)
* [ ] add somehow webextension technical documentation (already started as a markdown file in `/webextension`)
* [ ] and improve main README to at least include wiki's home & website's home contents.

Go, go go!

**Comment by notabene** [comment]
Congratulations are in order!
